name: ge
channels:
  - conda-forge
dependencies:
  - python=2.7
  - numpy
  - scipy
  - pysal
  - pandas
  - mdp
  - bottleneck
  - notebook
  - matplotlib-base
  - geopandas
  - descartes
  - shapely
